// <auto-generated />
using System;
using InkHouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InkHouse.Migrations
{
    [DbContext(typeof(InkHouseDbContext))]
    [Migration("20240629212934_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InkHouse.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("ed1dc00c-8576-4e3b-8a99-6c85ad9336b3"),
                            Name = "Франция"
                        },
                        new
                        {
                            CountryId = new Guid("e8c499d3-a794-49a7-a65e-f0ec0bcace58"),
                            Name = "Германия"
                        },
                        new
                        {
                            CountryId = new Guid("36d13b72-f356-4d0a-8364-c6f55e78e538"),
                            Name = "Англия"
                        });
                });

            modelBuilder.Entity("InkHouse.Models.Painter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Painters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb26a45a-120e-477f-9356-a3845f07af35"),
                            Birthdate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("ed1dc00c-8576-4e3b-8a99-6c85ad9336b3"),
                            Name = "Марсель",
                            Surname = "Руссо"
                        },
                        new
                        {
                            Id = new Guid("9791266f-620d-433f-aad4-1dede4052505"),
                            Birthdate = new DateTime(1980, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("e8c499d3-a794-49a7-a65e-f0ec0bcace58"),
                            Name = "Анри",
                            Surname = "Селин"
                        },
                        new
                        {
                            Id = new Guid("28ff85a5-63da-41c8-827b-2d69afc3b148"),
                            Birthdate = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("36d13b72-f356-4d0a-8364-c6f55e78e538"),
                            Name = "Франсуа",
                            Surname = "Дюпон"
                        });
                });

            modelBuilder.Entity("InkHouse.Models.Painting", b =>
                {
                    b.Property<Guid>("PaintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PainterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaintingId");

                    b.HasIndex("PainterId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            PaintingId = new Guid("27bad295-e53c-4060-8fb5-57681f1e4354"),
                            Image = "Assets/PaintingImg/27bad295-e53c-4060-8fb5-57681f1e4354.jpg",
                            Name = "Дама с собачкой",
                            PainterId = new Guid("9791266f-620d-433f-aad4-1dede4052505"),
                            Price = 16500.0,
                            Title = "Акрил, бумага (50х80)"
                        },
                        new
                        {
                            PaintingId = new Guid("7cea2648-a8fc-4cca-9730-85bf83ac437c"),
                            Image = "Assets/PaintingImg/7cea2648-a8fc-4cca-9730-85bf83ac437c.jpg",
                            Name = "Процедура",
                            PainterId = new Guid("28ff85a5-63da-41c8-827b-2d69afc3b148"),
                            Price = 20000.0,
                            Title = "Цветная литография (40х60)"
                        });
                });

            modelBuilder.Entity("InkHouse.Models.Painter", b =>
                {
                    b.HasOne("InkHouse.Models.Country", "Country")
                        .WithMany("Painters")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InkHouse.Models.Painting", b =>
                {
                    b.HasOne("InkHouse.Models.Painter", "Painter")
                        .WithMany("Paintings")
                        .HasForeignKey("PainterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painter");
                });

            modelBuilder.Entity("InkHouse.Models.Country", b =>
                {
                    b.Navigation("Painters");
                });

            modelBuilder.Entity("InkHouse.Models.Painter", b =>
                {
                    b.Navigation("Paintings");
                });
#pragma warning restore 612, 618
        }
    }
}
